select article, source_owner, publication
  from distribution.dbo.MSarticles a with (nolock)
    inner join distribution.dbo.MSpublications p on p.publication_id =a.publication_id
  where a.publisher_db = 'rmprod'
    --and article = 'iLaborOrdersInterfaceAudit'
order by publication
  --order by source_object

/*
Candidates
AccountApprovalHistory
AccountAssignment
AccountAssignmentHistory
AccountClassifications
AccountClassifications
activityGroup
ActivityResults
ActivityTriggers
asciixref
AssignmentEndReason
Audit
BranchAccountManagers
BranchAccountManagerSpecialities
BranchPhones
BranchSpecialities
BusinessUnit
CandidateCertifications
CandidateClearance
CandidateEmail
CandidateHistory
CandidateHistoryNRCOpenings
CandidateHotList
CandidateMergeHistory
CandidateMonsterResume
CandidateMonsterSeeker
CandidatePhones
CandidateRecruiters
CandidateSkills
CandidateSocialMedia
CandidateSourceAudit
CandidateSubmissions
CandidateTransportation
CandidateViewLog
Certification
ClientAccountClassification
ClientAccountManagers
ClientBranch
ClientContacts
clientlocationmoves
ClientOffices
ClientPhones
ClientProjections
ClientRecruiters
Clients
Company
CompanyBuyingModels
Competencies
contactDM
ContactPhones
CopyJobReasons
Countries
CustomerRollupGroups
CustomerRollups
DiscountsRebates
ecsbtsauditdetail
ECSMASTERLIST
Education
Emails
FallOutReason
FallOutReason_Lookup
folder
folderItem
folderItemType
folderRole
folderUser
FunctionalTitles
FunctionalTitles_Lookup
Guarantee
HireType
HistoryCategories
HistoryCategories_Lookup
HistoryCategoryResults
HistoryRecurrence
HistoryResults
IndustrySectors
IndustryTypes
IndustryXTaxonomies
intfcPlacementKey
intfcRMaxKey
intfcRMaxKeyLog
JobPriority
kpicrossreference
KPIGroupPSJobCode
KPIGroups
KPIRoles
MinorityOwnerCodes
Notes
nrcCallLog
nrcCallLogCandidateHistory
nrcCallLogCandidates
nrcCallLogHistory
nrcCallLogUserHistory
nrcCallLogUsers
nrcSplitActivity
Offices
OrderAccountManagers
OrderCandidateCommissions
OrderCandidateHistory
OrderCandidateRecruiter
OrderCandidates
Ordercandidatescsf
OrderCandidatesHistory
OrderCategory
OrderCategory_LookUp
OrderCosts
OrderDates
OrderNRCOpenings
OrderOccupations
OrderOpenings
OrderPayTypeAdditional
OrderRecruiters
OrderRecruiters2
OrderRecruiters3
Orders
OrderSkills
OrderSourceAudit
orderTravelAuthorizations
OrderTypes
OrderVendors
OrgLevel
OrgUnit
OrgUnitXSpecialties
Overtimerules
PayType
PayTypeAdditional
PayTypeAdditional_Lookup
PersonType
PhoneTypes
placementstoinactivate
productCodes
ReferralDetail
ReferralDetail_Lookup
ReferralType
ReferralType_Lookup
RejectedReasons
SavedSearches
SecurityClearance
SkillCategory
SkillClass
Skills
socialMediaTypes
Specialties
Stages
Stages_Lookup
States
Status
Status_Lookup
StatusReasons
SummaryProductCodes
SummaryProductCodes_LookUp
SupervisorAssignments
SystemApplicationRoles
Taxonomies
TempReasons
TimeEntrySystems
Transportation
TravelPercent
UserDefinedAnswers
UserDefinedFields
Users
VMSsystems
WorkSiteAddress
WorkSiteHistory
zipinfo
zipinfometroarealist
Zips

*/
